<?php
declare(strict_types=1);

use Kakeizu\App;

    if ($route==='/settings/relationships' && $method==='GET') {$u=owner();$q=$db->prepare('SELECT r.*,(SELECT COUNT(*) FROM chart_nodes n WHERE n.relationship_definition_id=r.id) usage_count FROM relationship_definitions r WHERE user_id=? ORDER BY sort_order,name');$q->execute([$u['id']]);App::ok(array_map('mapRelationship',$q->fetchAll()));}
    if ($route==='/settings/relationships' && $method==='POST') {$u=owner(true);$in=App::input();$name=text($in,'name',40);$publicKind=(string)($in['kind']??'');$direction=(string)($in['direction']??'');$style=(string)($in['lineStyle']??'');if(!in_array($publicKind,['self','parent','child','partner','sibling','divorce','other'],true)||!in_array($direction,['above','below','left','right'],true)||!in_array($style,['solid','dashed','dotted'],true)||!App::validColor($in['lineColor']??''))App::fail(422,'VALIDATION_ERROR','続柄の設定を確認してください');[$kind,$role]=storedRelationKind($publicKind);$id=App::id();$db->prepare('INSERT INTO relationship_definitions(id,user_id,name,kind,direction,line_style,line_color,sort_order,active,diagram_role) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$id,$u['id'],$name,$kind,$direction,$style,$in['lineColor'],(int)($in['sortOrder']??0),boolValue($in['active']??true),$role]);$q=$db->prepare('SELECT * FROM relationship_definitions WHERE id=?');$q->execute([$id]);App::ok(mapRelationship($q->fetch()),201);}
    if (preg_match('#^/settings/relationships/([a-f0-9]{32})$#',$route,$m)) {
        $u=owner(true);$old=relationshipOwned($m[1],$u['id']);
        if($method==='DELETE'){$q=$db->prepare('SELECT COUNT(*) FROM chart_nodes WHERE relationship_definition_id=?');$q->execute([$m[1]]);if((int)$q->fetchColumn()>0)App::fail(409,'MASTER_IN_USE','使用中の続柄は削除できません');$db->prepare('DELETE FROM relationship_definitions WHERE id=?')->execute([$m[1]]);App::ok();}
        if($method==='PATCH'){$in=App::input();$name=text(['name'=>$in['name']??$old['name']],'name',40);$publicKind=(string)($in['kind']??publicRelationKind($old));$direction=(string)($in['direction']??$old['direction']);$style=(string)($in['lineStyle']??$old['line_style']);$color=(string)($in['lineColor']??$old['line_color']);if(!in_array($publicKind,['self','parent','child','partner','sibling','divorce','other'],true)||!in_array($direction,['above','below','left','right'],true)||!in_array($style,['solid','dashed','dotted'],true)||!App::validColor($color))App::fail(422,'VALIDATION_ERROR','続柄の設定を確認してください');[$kind,$role]=storedRelationKind($publicKind);$db->prepare('UPDATE relationship_definitions SET name=?,kind=?,direction=?,line_style=?,line_color=?,sort_order=?,active=?,diagram_role=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$name,$kind,$direction,$style,$color,(int)($in['sortOrder']??$old['sort_order']),boolValue($in['active']??$old['active']),$role,$m[1]]);$q=$db->prepare('SELECT * FROM relationship_definitions WHERE id=?');$q->execute([$m[1]]);App::ok(mapRelationship($q->fetch()));}
    }
    if ($route==='/settings/genders' && $method==='GET') {$u=owner();$q=$db->prepare('SELECT g.*,(SELECT COUNT(*) FROM chart_nodes n WHERE n.gender_definition_id=g.id) usage_count FROM gender_definitions g WHERE user_id=? ORDER BY sort_order,name');$q->execute([$u['id']]);App::ok(array_map('mapGender',$q->fetchAll()));}
    if ($route==='/settings/genders' && $method==='POST') {$u=owner(true);$in=App::input();$name=text($in,'name',40);$shape=(string)($in['shape']??'');if(!in_array($shape,['circle','square','diamond'],true)||!App::validColor($in['fillColor']??'')||!App::validColor($in['textColor']??''))App::fail(422,'VALIDATION_ERROR','性別の設定を確認してください');$id=App::id();$db->prepare('INSERT INTO gender_definitions(id,user_id,name,shape,fill_color,text_color,sort_order,active) VALUES(?,?,?,?,?,?,?,?)')->execute([$id,$u['id'],$name,$shape,$in['fillColor'],$in['textColor'],(int)($in['sortOrder']??0),boolValue($in['active']??true)]);$q=$db->prepare('SELECT * FROM gender_definitions WHERE id=?');$q->execute([$id]);App::ok(mapGender($q->fetch()),201);}
    if (preg_match('#^/settings/genders/([a-f0-9]{32})$#',$route,$m)) {
        $u=owner(true);$old=genderOwned($m[1],$u['id']);
        if($method==='DELETE'){$q=$db->prepare('SELECT COUNT(*) FROM chart_nodes WHERE gender_definition_id=?');$q->execute([$m[1]]);if((int)$q->fetchColumn()>0)App::fail(409,'MASTER_IN_USE','使用中の性別は削除できません');$db->prepare('DELETE FROM gender_definitions WHERE id=?')->execute([$m[1]]);App::ok();}
        if($method==='PATCH'){$in=App::input();$name=text(['name'=>$in['name']??$old['name']],'name',40);$shape=(string)($in['shape']??$old['shape']);$fill=(string)($in['fillColor']??$old['fill_color']);$textColor=(string)($in['textColor']??$old['text_color']);if(!in_array($shape,['circle','square','diamond'],true)||!App::validColor($fill)||!App::validColor($textColor))App::fail(422,'VALIDATION_ERROR','性別の設定を確認してください');$db->prepare('UPDATE gender_definitions SET name=?,shape=?,fill_color=?,text_color=?,sort_order=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$name,$shape,$fill,$textColor,(int)($in['sortOrder']??$old['sort_order']),boolValue($in['active']??$old['active']),$m[1]]);$q=$db->prepare('SELECT * FROM gender_definitions WHERE id=?');$q->execute([$m[1]]);App::ok(mapGender($q->fetch()));}
    }
